---
global:
templates:
- '/etc/alertmanager/template/*.tmpl'
route:
  repeat_interval: 1m
  receiver: operations-team

receivers:
- name: 'operations-team'
  slack_configs:
  - api_url: https://hooks.slack.com/services/T013X2WHA3T/B0142E16P25/xxxxxxxxxxx
    channel: '#xalert'
    send_resolved: true
